# Generated by Django 4.0.3 on 2022-03-20 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='contacts',
            new_name='contact',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='decsription',
            new_name='desc',
        ),
    ]
